# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  issues:
    types: [opened ]
  issue_comment:
    types: [created ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
    runs-on: ubuntu-latest
    steps:
    - name: clone repository
      uses: actions/checkout@v2
    - name: download
      uses: undefined-ux/download-action@spilt-to-fit-max-size
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        url: 'magnet:?xt=urn:btih:04B0E8B4C42A3B7FBC222CB19681C18AE49C04D3&tr=http%3A%2F%2Fbt3.t-ru.org%2Fann%3Fmagnet&dn=Yamaha%20-%20Vocaloid%204.3.0%20x86%20%2B%20ALL%20Libraries%20%5B25.10.2016%5D'
        actor: ${{ github.actor }}
        repo: ${{ github.repository }}
